name: 🐛 Bug Report
description: Report an error to help improve the project
title: "BUG: Short description of the issue"
labels: [bug]
assignees: [soliberdev]

body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Bug Report
        Thanks for reporting a bug. Please fill out the following form as accurately as possible.

  - type: textarea
    id: bug-description
    attributes:
      label: 🐞 Bug Description
      description: Provide a clear description of the error.
      placeholder: A clear and concise description of what the issue is.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 🔁 Steps to Reproduce the Bug
      description: Step-by-step instructions to reproduce the error.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: ✅ Expected Behavior
      description: What was the expected behavior?
      placeholder: I expected it to...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 🖥️ Environment Information (optional)
      description: Relevant system and environment information.
      placeholder: |
        - OS: Windows 10
        - Browser: Chrome 125
        - Project version: 1.0.0

  - type: textarea
    id: screenshots
    attributes:
      label: 📷 Screenshots or Logs (optional)
      description: Attach screenshots or logs if they help explain the error.
      placeholder: Paste screenshots or logs here.

  - type: textarea
    id: additional-info
    attributes:
      label: 📌 Additional Information
      description: Any other relevant information.
      placeholder: Context, links, related issues, etc.
