name: 🐛 Bug Report
description: Report an error to help improve the project
title: "🐞 BUG: Short description of the issue"
labels: [bug]
assignees: [soliberdev]

body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Found a bug?
        No worries — thanks for taking the time to report it! Please fill out the info below so I can understand and fix it faster.

  - type: textarea
    id: bug-description
    attributes:
      label: 🐞 What's going wrong?
      description: Tell me what’s happening. Be as clear as you can.
      placeholder: Describe the issue you're seeing.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 🔁 How can we see it too?
      description: Walk me through the steps so I can try to reproduce the issue.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: ✅ What did you expect to happen?
      description: Let me know what you thought would happen instead.
      placeholder: I expected it to...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 🖥️ Where did this happen? (optional)
      description: Tell me about your system or setup, if it might help.
      placeholder: |
        - OS: Windows 10
        - Browser: Chrome 125
        - Project version: 1.0.0

  - type: textarea
    id: screenshots
    attributes:
      label: 📷 Screenshots or Logs (optional)
      description: Got an error message, console output, or a screenshot? Drop it here.
      placeholder: You can paste images or code logs here.

  - type: textarea
    id: additional-info
    attributes:
      label: 📌 Anything else?
      description: If there's more context, links, or related issues, include them here.
      placeholder: Context, related tickets, guesses about the cause, etc.
