name: ✨ Feature Request
description: Suggest a new feature or improvement for the project
title: "🚀 FEATURE: Short description of the idea"
labels: [improvement]
assignees: [soliberdev]

body:
  - type: markdown
    attributes:
      value: |
        ## ✨ Feature Request
        Thank you for your suggestion! Please fill out the following details to help me understand your idea better.

  - type: textarea
    id: feature-description
    attributes:
      label: ✨ What would you like to see?
      description: Describe the new feature or change you'd like me to add.
      placeholder: Tell me clearly what the feature is and what it should do.
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: 💡 Why is this important?
      description: Help me understand why this feature matters. What problem does it solve, or how would it make things better?
      placeholder: Explain why this feature would be helpful or valuable.
    validations:
      required: true

  - type: textarea
    id: suggested-implementation
    attributes:
      label: 🛠️ How could it work? (optional)
      description: If you have any ideas on how it could be built or work, write them here.
      placeholder: Share your thoughts on how it could be implemented.

  - type: textarea
    id: additional-resources
    attributes:
      label: 🔗 Extra info (optional)
      description: Include links, images, sketches, or anything else that helps explain your idea.
      placeholder: Add any relevant references or assets.
